### ISSUE TITLE
Unable to compile when using in typescript

### ISSUE THREAD

**Issue by realtebo** [nodejs/undici#3009] opened 2024-03-28 11:24 UTC
This code 

```
import { request } from 'undici';

export async function getDevices() {

  const catResult = await request('https://aws.random.cat/meow');
  return {};
}

```
gives me an unable to compile error

![image](https://github.com/nodejs/undici/assets/1268699/9c795095-f3ce-49f2-9356-b205adfef3de)

**Comment by ronag** [comment] 2024-03-28 12:17
PR welcome

**Comment by stu01509** [comment] 2024-03-28 15:16
Hi @realtebo 

I'm interested in this topic, are you using Next.js? Could you provide the details information, like Node.js, Next.js version?

Thanks.

**Comment by realtebo** [comment] 2024-03-28 15:29
```
 % node -v
v20.11.1
```

```
  "dependencies": {
    "@heroicons/react": "^2.1.3",
    "axios": "^1.6.8",
    "clsx": "^2.1.0",
    "dotenv": "^16.4.5",
    "next": "14.1.4",
    "next-auth": "^5.0.0-beta.16",
    "react": "^18",
    "react-dom": "^18",
    "undici": "^6.10.2",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.1.4",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
```

**Comment by tsctx** [comment] 2024-03-28 23:40
See #2954

**Comment by stu01509** [comment] 2024-03-29 01:59
Yeah, it seems like there's a problem with Next.js. 
I tried another TypeScript project, and it works for me.

**Comment by HelaGone** [comment] 2024-04-03 16:13
I've come to the same error. Is there a workaround? I'm using the latest version  next 14.1.4

**Comment by Uzlopak** [comment] 2024-04-06 22:39
Duplicate of #2954

**Closed by Uzlopak** 2024-04-06 22:39 UTC
