### ISSUE TITLE
100 coverage

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#539] opened 2021-02-07 10:44 UTC
We're down from 100 coverage again.

```
---------------------|----------|----------|----------|----------|-------------------|
File                 |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
---------------------|----------|----------|----------|----------|-------------------|
All files            |    99.64 |    98.59 |      100 |    99.63 |                   |
 undici              |      100 |      100 |      100 |      100 |                   |
  index.js           |      100 |      100 |      100 |      100 |                   |
 undici/lib          |      100 |    99.33 |      100 |      100 |                   |
  abort-signal.js    |      100 |      100 |      100 |      100 |                   |
  agent.js           |      100 |    92.59 |      100 |      100 |             22,71 |
  client-connect.js  |      100 |      100 |      100 |      100 |                   |
  client-pipeline.js |      100 |      100 |      100 |      100 |                   |
  client-request.js  |      100 |      100 |      100 |      100 |                   |
  client-stream.js   |      100 |      100 |      100 |      100 |                   |
  client-upgrade.js  |      100 |      100 |      100 |      100 |                   |
  pool.js            |      100 |      100 |      100 |      100 |                   |
 undici/lib/core     |    99.38 |     98.2 |      100 |    99.37 |                   |
  client.js          |    99.47 |     98.1 |      100 |    99.47 |       99,415,1116 |
  errors.js          |      100 |      100 |      100 |      100 |                   |
  request.js         |      100 |      100 |      100 |      100 |                   |
  symbols.js         |      100 |      100 |      100 |      100 |                   |
  util.js            |    97.33 |    96.34 |      100 |     97.3 |             68,69 |
 undici/lib/node     |      100 |      100 |      100 |      100 |                   |
  fixed-queue.js     |      100 |      100 |      100 |      100 |                   |
  http-parser.js     |      100 |      100 |      100 |      100 |                   |
---------------------|----------|----------|----------|----------|-------------------|
```

**Comment by ronag** [comment] 2021-02-07 10:45
I will sort this eventually. Feel free to take a shot at it if you want. @dnlup @Ethan-Arrowood

**Comment by simoneb** [comment] 2021-03-03 09:20
duplicate of https://github.com/nodejs/undici/issues/539

**Closed** 2021-03-03 09:28 UTC
Labels: good first issue, help wanted
