### ISSUE TITLE
request session

### ISSUE THREAD

**Issue by Automized** [nodejs/undici#1750] opened 2022-11-02 10:48 UTC
Hello, 

I just wanted to make this to ask how I would go about creating a request session (will carry all cookies throughout all requests in the session) or at least how I can use a cookie jar.

I have read the docs and cannot find anything about this, wanted to ask if I am missing something or that it just is not possible in undici.

Thank you.

**Comment by mcollina** [comment] 2022-11-02 10:59
This is a duplicate of #864. We do not have a cookie jar at the moment.

**Closed** 2022-11-02 10:59 UTC
