### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by kyrylkov** [nodejs/undici#1248] opened 2022-02-23 21:27 UTC
## Bug Description
Fetch throws 'TypeError: fetch failed' when posting

## Reproducible By
Request with private production credentials to ERP

## Expected Behavior
Successful response (ok).  `node-fetch` works just fine.

## Logs & Screenshots
```
 TypeError: fetch failed
    at Object.processResponse (C:\Users\kyryl\dev\entriwise\server\node_modules\undici\lib\fetch\index.js:183:23)
    at Fetch.fetchFinale (C:\Users\kyryl\dev\entriwise\server\node_modules\undici\lib\fetch\index.js:937:17)
    at Fetch.mainFetch (C:\Users\kyryl\dev\entriwise\server\node_modules\undici\lib\fetch\index.js:744:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Environment
Linux and Windows, v17.5 v17.6

### Additional context
Request takes up to several minutes until response

**Comment by mcollina** [comment] 2022-02-24 09:14
Thanks for reporting, would you like to include a code to reproduce your problem? We'd also need the server counterpart.

**Comment by kyrylkov** [comment] 2022-02-24 16:33
@mcollina We cannot share production environment credentials, but we could give you sandbox credentials via remote desktop.  Is there any other way to give you more info for debugging?

**Comment by mcollina** [comment] 2022-02-24 16:36
I think it would be better if you produced a server that returned that kind of response. We do not provide support for private code.

**Comment by kyrylkov** [comment] 2022-02-24 17:06
Matteo, the server is NetSuite ERP, so we cannot provide it.  Also note we've replaced undici fetch with `node-fetch` and it's working fine.

**Comment by mcollina** [comment] 2022-02-24 17:09
There is something in that server response that it is making undici.fetch fail. What I'm asking is a way to reproduce this without touching your systems. Only you can write it.

**Comment by kyrylkov** [comment] 2022-02-24 17:11
Right but I don't understand how?  The only way we can reproduce is ourselves is by executing that request to that account with those credentials.

**Comment by Linkgoron** [comment] 2022-02-24 18:25
There's supposed to be an additional `cause` property on that error, but I don't see it in the log. Does it exist?

**Comment by kyrylkov** [comment] 2022-02-24 19:00
@Linkgoron No.  The code is like this.  But 2nd line is never reached.

```
const fetchRes = await fetch(webservicesUrl, options);
if (!fetchRes.ok) throw new Error(`HTTP error! Status: ${fetchRes.status}`);
```

**Comment by ronag** [comment] 2022-02-24 19:16
Sorry but with this little information it's impossible for us to do anything.

**Comment by kyrylkov** [comment] 2022-02-24 19:47
@ronag So I'm trying to get you more information.  Can we add some debugging code in undici to help you diagnose it?

**Comment by janat08** [comment] 2022-02-24 21:34
I also get some error, it's not the same:
```
"TypeError: fetch failed\n    at Object.processResponse (C:\\Users\\jeyan\\Documents\\boughtwithslowsearch\\node_modules\\undici\\lib\\fetch\\index.js:183:23)\n    at Fetch.fetchFinale (C:\\Users\\jeyan\\Documents\\boughtwithslowsearch\\node_modules\\undici\\lib\\fetch\\index.js:937:17)\n    at Fetch.mainFetch (C:\\Users\\jeyan\\Documents\\boughtwithslowsearch\\node_modules\\undici\\lib\\fetch\\index.js:744:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
```

**Comment by akauppi** [comment] 2022-02-27 20:44
As a continuation to my above report, from a CI run.

It looks like Undici (4.14.1) `fetch` may have a general problem with host names. Here, `emul` is supposed to point to a Docker container under Google Cloud Build. The run fails to find it.

```
Step #2: > ci:test
Step #2: > wait-for emul:6767 && wait-for emul:5002 && npm run -s _ci_warm-up && npm run -s _test1
Step #2: 
Step #2: Unexpected error: TypeError: fetch failed
Step #2:     at Object.processResponse (/workspace/node_modules/undici/lib/fetch/index.js:183:23)
Step #2:     at Fetch.fetchFinale (/workspace/node_modules/undici/lib/fetch/index.js:937:17)
Step #2:     at Fetch.mainFetch (/workspace/node_modules/undici/lib/fetch/index.js:744:17)
Step #2:     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
Step #2:   cause: Error: getaddrinfo ENOTFOUND emul
Step #2:       at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
Step #2:     errno: -3008,
Step #2:     code: 'ENOTFOUND',
Step #2:     syscall: 'getaddrinfo',
Step #2:     hostname: 'emul'
Step #2:   }
```

**Comment by ronag** [comment] 2022-02-27 20:59
I don't think this has anything to do with undici per se. Does it work with the normal `http` client in node?

**Comment by ronag** [comment] 2022-02-28 17:40
@akauppi: Sorry but I don't think this is an issue we can resolve in undici. Sounds more like a node core thing.

**Comment by ronag** [comment] 2022-03-19 07:48
@akauppi: As i wrote above undici is probably not the place for the fix.
@kyrylkov: If you want help with private code you can mail me.

**Comment by kyrylkov** [comment] 2022-04-26 11:40
@ronag I'm still having these error.  Cannot use undici fetch at all.  Here is update trace from Node v18:

```
TypeError: fetch failed
    at Object.processResponse (/home/ubuntu/server/node_modules/undici/lib/fetch/index.js:200:23)
    at /home/ubuntu/server/node_modules/undici/lib/fetch/index.js:941:38
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    ... 2 lines matching cause stack trace ...
    at process.processTimers (node:internal/timers:507:7) {
  cause: Error: [object Object]
      at makeNetworkError (/home/ubuntu/server/node_modules/undici/lib/fetch/response.js:366:11)
      at httpNetworkFetch (/home/ubuntu/server/node_modules/undici/lib/fetch/index.js:1751:12)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at runNextTicks (node:internal/process/task_queues:64:3)
      at listOnTimeout (node:internal/timers:533:9)
      at process.processTimers (node:internal/timers:507:7)
      at async httpNetworkOrCacheFetch (/home/ubuntu/server/node_modules/undici/lib/fetch/index.js:1440:29)
      at async httpFetch (/home/ubuntu/server/node_modules/undici/lib/fetch/index.js:1028:33)
      at async schemeFetch (/home/ubuntu/server/node_modules/undici/lib/fetch/index.js:888:14)
      at async /home/ubuntu/server/node_modules/undici/lib/fetch/index.js:569:16
      at async mainFetch (/home/ubuntu/server/node_modules/undici/lib/fetch/index.js:553:16) {
    [cause]: undefined
  }
}

@ronag Could you re-open or reply to my emails?

**Comment by ItzaMi** [comment] 2022-08-15 08:16
> Had the same issue, had to switch from node v18 to v16 as a temp workaround.

This worked for me. Also was having the same issue without any resolution and downgrading to `16` ended up doing the trick!

**Comment by kyrylkov** [comment] 2022-08-15 08:57
We also keep getting this error from time to time in Node.js 18.7.0

**Comment by mcollina** [comment] 2022-08-15 08:58
I think I know what the problem is.

In node v17 we switched the default ordering of dns entries to follow what the OS is providing us vs reordering to put ipv4 always first.

I _think_ we should try multiple addresses when dealing with localhost when establishing a new connection.

Wdyt @ronag?

**Comment by ronag** [comment] 2022-08-15 09:01
> I think I know what the problem is.
> 
> In node v17 we switched the default ordering of dns entries to follow what the OS is providing us vs reordering to put ipv4 always first.
> 
> I _think_ we should try multiple addresses when dealing with localhost when establishing a new connection.
> 
> Wdyt @ronag?

SGTM!

**Comment by mcollina** [comment] 2022-08-16 13:05
Closing in favor of https://github.com/nodejs/undici/issues/1602, it's clearer.

**Closed by mcollina** 2022-08-16 13:05 UTC
Labels: bug

**Comment by aegonwolf** [comment] 2022-09-04 15:22
Hello, I have been told I should post my example here as well since I might have the same error:
https://stackoverflow.com/questions/73599889/fastapi-refuses-connection-on-a-parameterized-endpoint-if-called-sequentially-wi?noredirect=1#comment129970573_73599889
I am using svelte and fastapi and it seems that I can not fetch two endpoints together but only one of them each.

**Comment by zvictor** [comment] 2022-09-05 07:38
As a temporary solution, please try [this](https://stackoverflow.com/a/72416352/599991):
```js
// Workaround from https://stackoverflow.com/a/72416352/599991
const dns = require('node:dns')
dns.setDefaultResultOrder('ipv4first')
```

**Comment by bnb** [comment] 2022-09-17 21:40
FWIW that doesn't solve the bug for me @zvictor

**Comment by kyrylkov** [comment] 2022-09-17 21:46
@zvictor It doesn't look like DNS issue because it happen after a whole bunch of previous similar request complete successfuly.

**Comment by mcollina** [comment] 2022-09-18 07:24
@bnb if that doesn't solve the problem... I would definitely need a client/server combo
that reproduces the problem.

**Comment by bnb** [comment] 2022-09-18 16:06
FWIW after a bit more tweaking it _seems_ to have solved it (or at least, it's working now)

**Comment by mcollina** [comment] 2022-09-18 20:37
what was the problem?

**Comment by bnb** [comment] 2022-09-18 20:49
I _believe_ the above code sample worked _after_ I'd completely reverted all the changes I'd made to my tests in attempts to get this functionality to work. You can find the working code [here](https://github.com/cutenode/nodevu/blob/e4927efa7b017c7d495366b8ac99f13e224e7f87/core/test/test.js)

**Comment by sugoidesune** [comment] 2023-03-02 08:09
So this just started happening out of the blue.  Working with firebase functions. From one minute to the next.
I didn't make any changes to my environment nor did i update or install packages between the time it worked and when it stopped.
Restarted Firebase functions and it works again...

```error
TypeError: fetch failed
>      at Object.fetch (node:internal/deps/undici/undici:14152:11)
>      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>    cause: ConnectTimeoutError: Connect Timeout Error
>        at onConnectTimeout (node:internal/deps/undici/undici:7967:28)
>        at node:internal/deps/undici/undici:7925:50
>        at Immediate._onImmediate (node:internal/deps/undici/undici:7954:37)
>        at process.processImmediate (node:internal/timers:476:21) {
>      code: 'UND_ERR_CONNECT_TIMEOUT'
>    }
>  }
> Node.js v18.14.0
```

**Comment by jpcmf** [comment] 2023-04-05 17:55
I'm facing the same issue with Next.js and Strapi. In localhost, the Next.js app can't fetch the API from Strapi. I recently updated Node.js to version 18.15.0.
```
error - TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchQuery (webpack-internal:///./src/utils/fetch.ts:18:22)
    at async Promise.all (index 0)
    at async getServerSideProps (webpack-internal:///./src/pages/index.tsx:47:20) {
  cause: Error: connect ECONNREFUSED ::1:1337
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 1337
  },
  page: '/'
}
```

**Comment by gazhay** [comment] 2023-04-15 18:14
Just hit this same bug. 
No real changes to code, other fetches, curl, etc work fine

```TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11118:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: InvalidArgumentError: invalid connection header
```

**Comment by kyrylkov** [comment] 2023-05-01 19:12
@mcollina Could you please re-open as this started happening again in Node.js 20 with latest fetch and timeout of 5 minutes.

**Comment by hholst80** [comment] 2023-05-02 10:38
> Closing in favor of #1602, it's clearer.

@kyrylkov

**Comment by kyrylkov** [comment] 2023-05-02 11:18
@hholst80 They are not related https://github.com/nodejs/undici/issues/1602#issuecomment-1216654581

No localhost involved in our case.

**Comment by fyapy** [comment] 2023-05-08 00:38
+1

**Comment by Ofonna-N** [comment] 2023-05-10 16:31
> I'm facing the same issue with Next.js and Strapi. In localhost, the Next.js app can't fetch the API from Strapi. I recently updated Node.js to version 18.15.0.
> 
> ```
> error - TypeError: fetch failed
>     at Object.fetch (node:internal/deps/undici/undici:11413:11)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async fetchQuery (webpack-internal:///./src/utils/fetch.ts:18:22)
>     at async Promise.all (index 0)
>     at async getServerSideProps (webpack-internal:///./src/pages/index.tsx:47:20) {
>   cause: Error: connect ECONNREFUSED ::1:1337
>       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
>     errno: -4078,
>     code: 'ECONNREFUSED',
>     syscall: 'connect',
>     address: '::1',
>     port: 1337
>   },
>   page: '/'
> }
> ```

Hi, did you ever solve this issue?

**Comment by kyrylkov** [comment] 2023-05-10 20:06
We didn't solve it.  It pops up once in a while.  We're looking at migrating away from undici or Node.js altogether.

**Comment by stormsson** [comment] 2023-05-12 20:26
Same issue here, fetching a remote url, not localhost :(

**Comment by jayco** [comment] 2023-05-14 22:47
Not sure if this a Node or a Undici thing, but I was getting the same issue and it was pretty confusing.

I did some debugging, I downgraded from latest 20 to LTS, and in my case, the difference looks to be in the way the error is being handled.

Same code for each below, just different node versions.

LTS 18.6.0
```
Error: 401:Unauthorized - invalid_token: The access token is invalid or has expired
    at list (webpack-internal:///(sc_server)/./lib/helpscout/client/list.ts:36:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GET (webpack-internal:///(sc_server)/./app/api/hello/route.ts:18:18)
    at async eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:240:37)
```

Node 20.1.0
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11522:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error [ERR_SOCKET_CONNECTION_TIMEOUT]: Socket connection timeout
      at new NodeError (node:internal/errors:399:5)
      at internalConnectMultiple (node:net:1099:20)
      at Timeout.internalConnectMultipleTimeout (node:net:1638:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ERR_SOCKET_CONNECTION_TIMEOUT'
  }
}
```

**Comment by marco-digennaro** [comment] 2023-05-20 09:57
+1 node v20, simple fetch request, suddenly, no code changes

`TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11522:11) {
  cause: SocketError: other side closed
      at Socket.onSocketEnd (node:internal/deps/undici/undici:9740:26)
      at Socket.emit (node:events:523:35)
      at endReadableNT (node:internal/streams/readable:1367:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',`

**Comment by offminded** [comment] 2023-05-21 16:41
I was having the same issue with node server in my dev env and fixed it using NODE_TLS_REJECT_UNAUTHORIZED=0 flag running the node server. My GraphQL server is using a self-signed certificate so the issue was related to nodejs issue with the SSL.

**Comment by kyrylkov** [comment] 2023-05-21 17:01
@offminded None of our issues related to self-signed certificated as they happen in production against well known URLs and certificates.

**Comment by BSN4** [comment] 2023-06-04 07:16
same here try :

```js

    const bug = await fetch('https://fapi.binance.com/fapi/v1/exchangeInfo')
    console.log(bug.json())
    
   ```

**Comment by BSN4** [comment] 2023-06-04 13:21
I don't want to open new bug issue , because we already have one with all things you need @mcollina @RafaelGSS  can you please reopen this issue... i've decided to downgrade my node version from 20.2.0 to 18.16.0 because of this

**Comment by kyrylkov** [comment] 2023-06-04 14:28
@BSN4 your example works just fine for me, returning 

```
{
  code: 0,
  msg: "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}
```

**Comment by BSN4** [comment] 2023-06-04 14:59
for was `TypeError: fetch failed`.. so this is node v20.2.0 not sure why isn't working, but on v18.16.0 it works I suspect cloudflare being the issue here

**Comment by kyrylkov** [comment] 2023-06-04 15:27
@BSN4 We need a case to consistently reproduce `fetch failed`.  But your case works fine for me.

**Comment by anovicenko74** [comment] 2023-06-16 12:35
> Я сталкиваюсь с той же проблемой с Next.js и Strapi. На localhost Next.js приложение не может получить API из Strapi. Недавно я обновил Node.js до версии 18.15.0.
> 
> ```
> error - TypeError: fetch failed
>     at Object.fetch (node:internal/deps/undici/undici:11413:11)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async fetchQuery (webpack-internal:///./src/utils/fetch.ts:18:22)
>     at async Promise.all (index 0)
>     at async getServerSideProps (webpack-internal:///./src/pages/index.tsx:47:20) {
>   cause: Error: connect ECONNREFUSED ::1:1337
>       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
>     errno: -4078,
>     code: 'ECONNREFUSED',
>     syscall: 'connect',
>     address: '::1',
>     port: 1337
>   },
>   page: '/'
> }
> ```

I also implement authorization with strapi and next. I had a fetch error. The only thing that helped me was this combination of environment variables: NEXTAUTH_URL=http:localhost:3000 NEXT_PUBLIC_API_URL=http://127.0.0.1:1337

**Comment by sangdth** [comment] 2023-07-08 13:31
I removed  the line `::1 localhost`, things work again in my Nextjs case.

**Comment by kyrylkov** [comment] 2023-07-08 13:38
> I removed the line `::1 localhost` like this [comment](https://github.com/nodejs/undici/issues/1248#issuecomment-1054467140), things work again in my Nextjs case.

It's not related to localhost in many cases.

**Comment by BSN4** [comment] 2023-07-08 19:42
Im not sure why but seems the team decided to ignore this bug ?

Any news about this issue

**Comment by kyrylkov** [comment] 2023-07-08 19:50
> Im not sure why but seems the team decided to ignore this bug ?

No one has provide a repro for them to look into

**Comment by BSN4** [comment] 2023-07-13 11:20
@kyrylkov ok tested this on v20.4.0 I think its fixed for now can't say for sure

**Comment by kyrylkov** [comment] 2023-07-13 17:02
> ok tested this on v20.4.0 I think its fixed for now can't say for sure

We have this issue with v20.4.0 also

**Comment by jpcmf** [comment] 2023-07-16 21:09
> > Я сталкиваюсь с той же проблемой с Next.js и Strapi. На localhost Next.js приложение не может получить API из Strapi. Недавно я обновил Node.js до версии 18.15.0.
> > ```
> > error - TypeError: fetch failed
> >     at Object.fetch (node:internal/deps/undici/undici:11413:11)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> >     at async fetchQuery (webpack-internal:///./src/utils/fetch.ts:18:22)
> >     at async Promise.all (index 0)
> >     at async getServerSideProps (webpack-internal:///./src/pages/index.tsx:47:20) {
> >   cause: Error: connect ECONNREFUSED ::1:1337
> >       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
> >     errno: -4078,
> >     code: 'ECONNREFUSED',
> >     syscall: 'connect',
> >     address: '::1',
> >     port: 1337
> >   },
> >   page: '/'
> > }
> > ```
> 
> I implement authorization with strapi and next. I had a fetch error. The only thing that helped me was this combination of environment variables: NEXTAUTH_URL=http:localhost:3000 NEXT_PUBLIC_API_URL=http://127.0.0.1:1337
> 
> https://strapi.io/blog/user-authentication-in-next-js-with-strapi

I did the same. I replaced "localhost" with "127.0.0.1"  👎🏻

**Comment by gigantino** [comment] 2023-07-30 17:25
Having the same issue, downgrading to 18.16.0 solved it.

**Comment by pauldraper** [comment] 2023-07-31 23:22
The problem is that `error.stack` does not include the cause.

```js
new Error("", { cause: new Error() }).stack
```

```txt
Error
    at [eval]:1:13
    at Script.runInThisContext (node:vm:128:12)
    at Object.runInThisContext (node:vm:306:38)
    at node:internal/process/execution:83:21
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:82:62)
    at evalScript (node:internal/process/execution:104:10)
    at node:internal/main/eval_string:50:3
```

Whereas

```js
util.inspect(new Error("", { cause: new Error() }))
```

```txt
Error
    at [eval]:1:37
    at Script.runInThisContext (node:vm:128:12)
    ... 5 lines matching cause stack trace ...
    at node:internal/main/eval_string:50:3 {
  [cause]: Error
      at [eval]:1:60
      at Script.runInThisContext (node:vm:128:12)
      at Object.runInThisContext (node:vm:306:38)
      at node:internal/process/execution:83:21
      at [eval]-wrapper:6:24
      at runScript (node:internal/process/execution:82:62)
      at evalScript (node:internal/process/execution:104:10)
      at node:internal/main/eval_string:50:3
```

That `cause` will show you the real problem with the request. E.g. if you try to send an expect header, or an invalid connection header, or a million other possible problems.

You'll need to fix the logging to include the cause, not just the stack.

**Comment by kyrylkov** [comment] 2023-08-01 04:53
@pauldraper You're right about the cause.  But disregarding whether logging includes the cause or not, there is a clearly something wrong with various version of undici / Node.js.  Because with some combinations of undici / Node.js versions `TypeError: fetch failed` doesn't happen and with some it happens consistently often, whatever the underlying cause is.

**Comment by pauldraper** [comment] 2023-08-01 04:59
> whatever the underlying cause is

Well, that's actually pretty significant.

I recommend posting the cause.

**Comment by kyrylkov** [comment] 2023-08-01 05:23
It is significant, but even more significant is the repro, which no one could produce so far because the issue is intermittent and not easily reproducible.  In our case, for example, when it fails, it fails in like 1 request out of 1000.  And as soon as we log the request and retry it, it works just fine without producing the error.

**Comment by pauldraper** [comment] 2023-08-01 07:21
It could be, for example, a network failure. No way to know here.

**Comment by kyrylkov** [comment] 2023-08-01 11:15
It can be, but it is not.  Why?  Because it happens only with a certain combination with Node / undici.  And it doesn't happen at all with other combinations.  Thus it is a Node / undici issue.

**Comment by pauldraper** [comment] 2023-08-01 11:55
This happened to me a few hours ago. I logged the cause.

```txt
cause: HeadersTimeoutError: Headers Timeout Error
```

**Comment by ronag** [comment] 2023-08-02 04:49
That happens when the server hasn't replied with anything in a minute or so.

**Comment by ronag** [comment] 2023-08-02 04:49
I think some of these issue might be related to keep-alive + server or client bugs. Try to disable keep-alive and see if the issue persists.

**Comment by kyrylkov** [comment] 2023-08-02 06:12
> > This happened to me a few hours ago. I logged the cause.
> 
> That happens when the server hasn't replied with anything in a minute or so.

For unidici fetch, at one time, this was changed to 5 minutes.  5 minute header time is very unlikely.  Unless again this has been reverted to 1 minute.

**Comment by gazhay** [comment] 2023-08-02 15:22
Fwiw my report wasn't timeout related as the error was instantaneous in all cases.

**Comment by utmp** [comment] 2023-08-06 11:29
Suddenly I started facing fetch issue while making a  nextjs app. Everything was working fine last night. 


```
$ node -v
v18.16.1
```

` TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (/home/xu/Desktop/route-draw/node_modules/next/dist/compiled/undici/index.js:1:82152)
      at /home/xu/Desktop/route-draw/node_modules/next/dist/compiled/undici/index.js:1:81644
      at Immediate._onImmediate (/home/xu/Desktop/route-draw/node_modules/next/dist/compiled/undici/index.js:1:82034)
      at process.processImmediate (node:internal/timers:476:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
`

**Comment by arun1940** [comment] 2023-08-07 08:54
I am facing an issue while sending a GET request with body data. The error disappears when I remove the body data. But when I send a POST request with a body, the error doesn't occur. My current version of Next.js is 13.4, and I suspect that the error is caused by trying to send a GET request with body data.

**Comment by kyrylkov** [comment] 2023-08-07 08:59
@arun1940 We had it both with GET without body and with many POSTs.

**Comment by utmp** [comment] 2023-08-07 09:04
> I am facing an issue while sending a GET request with body data. The error disappears when I remove the body data. But when I send a POST request with a body, the error doesn't occur. My current version of Next.js is 13.4, and I suspect that the error is caused by trying to send a GET request with body data.

```
From the [HTTP 1.1 2014 Spec](https://www.rfc-editor.org/rfc/rfc7231#page-24):

    A payload within a GET request message has no defined semantics; sending a payload body on a GET request might cause some existing implementations to reject the request.
```

Try it check with node-fetch, import this

`javascript
import fetch from 'node-fetch';
`

**Comment by arun1940** [comment] 2023-08-07 09:29
I managed to resolve my issue by removing the data from the body of the GET request. I was using Postman to test my API and my application is built on Next.js version 13.4. The error that was occurring has been resolved.- error Failed to handle a request for /api/xxx-xx
My Error Was:-
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at async invokeRequest (/home//nextjs/auth-app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
    at async requestHandler (/home/xxxx/nextjs/auth-app/node_modules/next/dist/server/lib/start-server.js:336:33)
    at async Server.<anonymous> (/home/xxxx/nextjs/auth-app/node_modules/next/dist/server/lib/start-server.js:152:13) {
  cause: RequestContentLengthMismatchError: Request body length does not match content-length header
      at write (node:internal/deps/undici/undici:9949:41)
      at _resume (node:internal/deps/undici/undici:9927:33)
      at resume (node:internal/deps/undici/undici:9829:7)
      at connect (node:internal/deps/undici/undici:9818:7) {
    code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
  }
}

**Comment by GermanCastroJurado** [comment] 2023-08-10 20:52
I'm having the same problem in Next.js version 13.4 with node version18.12.1.  
@arun1940 Can you be more explicit on how you solved the problem removing the data from the body of the GET request? 
My problem occurs with a 'POST' request and I need the header and body data.

**Comment by 0oj** [comment] 2023-08-12 19:46
> I don't think it's a network failure. On SvelteKit (which is where I got this error), once it happens once it keeps on happening multiple times (even if I restart node) and then just randomly decides to start working again. I also thought it could have been a network issue but everything else worked perfectly...

@gigantino We're you able to resolve this within SvelteKit? I'm facing the same issue trying to access a certain LinkedIn endpoint (others work fine). Exact same behaviour. Randomly works sometimes when I'm not looking.

**Comment by gigantino** [comment] 2023-08-12 21:40
> @gigantino We're you able to resolve this within SvelteKit? I'm facing the same issue trying to access a certain LinkedIn endpoint (others work fine). Exact same behaviour. Randomly works sometimes when I'm not looking.

@0oj I did by switching to Node 18.16.0

**Comment by HermesKD123** [comment] 2023-08-19 14:12
Hello, anyone got the fix to this error?

**Comment by BeanKorea** [comment] 2023-08-23 05:29
This issue is happening in @microsoft/signalr

**Comment by ronag** [comment] 2023-08-23 05:34
This is a generic error that can occur due to several different reasons. Please check the cause property on the error.
