### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by harshmangalam** [nodejs/undici#1857] opened 2023-01-14 16:22 UTC
## Bug Description

I am using ffmpeg in sveltekit to generate thumbnail from video but when ffmpeg start loading i am getting error from undici.
This is the file from where error occurs

```ts
import { createFFmpeg } from "@ffmpeg/ffmpeg";
const ffmpeg = createFFmpeg({ log: true });

async function generateThumbnail(videoData: Uint8Array) {
  await ffmpeg.load();
  const inputFileName = `input-video`;
  const outputFileName = `thumbnail.webp`;

  ffmpeg.FS("writeFile", inputFileName, videoData);

  await ffmpeg.run(
    "-ss",
    "00:00:01.000",
    "-i",
    inputFileName,
    "-frames:v",
    "1",
    outputFileName
  );
}

export { generateThumbnail };


```

## Logs

```
[info] use ffmpeg.wasm v0.11.6
[info] load ffmpeg-core
[info] loading ffmpeg-core
fetch failed
TypeError: fetch failed
    at fetch (C:\Users\ACER\development\svelte-kit\sveltetube\node_modules\.pnpm\undici@5.14.0\node_modules\undici\index.js:105:13)
```

## Environment

  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 11.56 GB / 19.78 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22000.120

**Comment by mcollina** [comment] 2023-01-14 19:46
Can you make that script self-runnable?

**Comment by mcollina** [comment] 2023-01-14 19:46
Does this happen without sveltekit?

**Comment by harshmangalam** [comment] 2023-01-15 03:35
> Does this happen without sveltekit?

I have used ffmpeg with solidjs working fine.

**Comment by silverwind** [comment] 2023-01-16 11:20
The code that logs the error should include `error.prototype.cause` which should hold more valuable debug information. Most likely this is a network error.

**Comment by ronag** [comment] 2023-01-16 11:25
We don't have sufficient information to do anything here...

**Comment by silverwind** [comment] 2023-01-16 11:29
Improving the error message on network error would be actionable (e.g. include the failing URL and error code), but I would consider it a breaking change as there are already [modules that test the current message](https://github.com/sindresorhus/p-retry/blob/285fdc3f890a6f3d199b3d4abb0bad7c172c2233/index.js#L3-L9). Maybe make another issue for this topic.

As for this specific issue, I would close it, it's very likely just a network error.

**Comment by harshmangalam** [comment] 2023-01-18 14:39
```
[info] use ffmpeg.wasm v0.11.6
[info] load ffmpeg-core
[info] loading ffmpeg-core
TypeError: fetch failed
    at fetch (C:\Users\ACER\development\svelte-kit\sveltetube\node_modules\.pnpm\undici@5.14.0\node_modules\undici\index.js:105:13) {
  cause: Error: unknown scheme
      at makeNetworkError (C:\Users\ACER\development\svelte-kit\sveltetube\node_modules\.pnpm\undici@5.14.0\node_modules\undici\lib\fetch\response.js:351:9)
      at schemeFetch (C:\Users\ACER\development\svelte-kit\sveltetube\node_modules\.pnpm\undici@5.14.0\node_modules\undici\lib\fetch\index.js:893:14)
      at C:\Users\ACER\development\svelte-kit\sveltetube\node_modules\.pnpm\undici@5.14.0\node_modules\undici\lib\fetch\index.js:602:22
      at mainFetch (C:\Users\ACER\development\svelte-kit\sveltetube\node_modules\.pnpm\undici@5.14.0\node_modules\undici\lib\fetch\index.js:652:7)
      at fetching (C:\Users\ACER\development\svelte-kit\sveltetube\node_modules\.pnpm\undici@5.14.0\node_modules\undici\lib\fetch\index.js:517:3)
      at fetch (C:\Users\ACER\development\svelte-kit\sveltetube\node_modules\.pnpm\undici@5.14.0\node_modules\undici\lib\fetch\index.js:245:16)
      at fetch (C:\Users\ACER\development\svelte-kit\sveltetube\node_modules\.pnpm\undici@5.14.0\node_modules\undici\index.js:103:20)
      at C:\Users\ACER\development\svelte-kit\sveltetube\node_modules\.pnpm\@ffmpeg+core@0.11.0\node_modules\@ffmpeg\core\dist\ffmpeg-core.js:215:32
      at C:\Users\ACER\development\svelte-kit\sveltetube\node_modules\.pnpm\@ffmpeg+core@0.11.0\node_modules\@ffmpeg\core\dist\ffmpeg-core.js:215:254
      at C:\Users\ACER\development\svelte-kit\sveltetube\node_modules\.pnpm\@ffmpeg+core@0.11.0\node_modules\@ffmpeg\core\dist\ffmpeg-core.js:215:277 {
    [cause]: undefined
  }
}

```

**Comment by ronag** [comment] 2023-01-18 14:41
`unknown scheme` how does the request url look?

**Comment by harshmangalam** [comment] 2023-01-18 14:58
I am not making any request only trying to utilize ffmpeg  for thumbnail.

**Comment by ronag** [comment] 2023-01-18 16:09
> I am not making any request only trying to utilize ffmpeg for thumbnail.

I don't think we can help you then. As far as I can see the problem is not in undici.

**Closed** 2023-01-20 08:35 UTC
Labels: bug

**Comment by nebrius** [comment] 2023-11-04 22:42
I just ran into this issue too. I figured out what's going on and thought I might post it here for posterity: it's a problem in emscripten itself when trying to run this on Windows (and maybe other OSes?). When building a wasm file, it uses `fetch` to load local files by default when available. Specifically, it generates this output for me:

```JavaScript
function getBinaryPromise(binaryFile) {
  // If we don't have the binary yet, try to load it asynchronously.
  // Fetch has some additional restrictions over XHR, like it can't be used on a file:// url.
  // See https://github.com/github/fetch/pull/92#issuecomment-140665932
  // Cordova or Electron apps are typically loaded from a file:// url.
  // So use fetch if it is available and the url is not a file, otherwise fall back to XHR.
  if (!wasmBinary
      && (ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER)) {
    if (typeof fetch == 'function'
    ) {
      return fetch(binaryFile, { credentials: 'same-origin' }).then((response) => {
        if (!response['ok']) {
          throw "failed to load wasm binary file at '" + binaryFile + "'";
        }
        return response['arrayBuffer']();
      }).catch(() => getBinarySync(binaryFile));
    }
  }

  // Otherwise, getBinarySync should be able to get it synchronously
  return Promise.resolve().then(() => getBinarySync(binaryFile));
}
```

Now that `fetch` is native in Node.js, this code defaults to trying to load the `.wasm` file using `fetch`. On Windows at least, `binaryFile`  is just a file path _without_ `file:` at the beginning of it, and thus not a valid URI schema (hence the error).

The fix is to update emscripten and recompile the C++ source code.

In the case of ffmpeg, it's probably been fixed in a newer release (hopefully).
