### ISSUE TITLE
Remove usages of ??= operators throught the library

### ISSUE THREAD

**Issue by matthewlilley** [nodejs/undici#1397] opened 2022-05-02 17:22 UTC
## Bug Description

There library is targeting Node 14 & 16, but contains usages of the ??= operator which is blocking production builds for various apps which are locked into Node 14. One was recently replaced, but there's at least one more... 

## Reproducible By

Consuming library in Node.js v14 environment

## Expected Behavior

Should run in Node.js v14 as expected

## Logs & Screenshots

```
this[kHeadersList][kHeadersSortedMap] ??= new Map([...this[kHeadersList]].sort((a, b) => a[0] < b[0] ? -1 : 1))
```

## Environment

Ubuntu 18.04 LTS,
Node lts/fermium

### Additional context

Previous PR replacing another of these operators:

https://github.com/nodejs/undici/pull/1318

**Comment by targos** [comment] 2022-05-02 17:38
All commits are tested on Node.js 14: https://github.com/nodejs/undici/runs/6260101390?check_suite_focus=true
How is it that CI doesn't catch this?

**Comment by matthewlilley** [comment] 2022-05-02 17:40
> All commits are tested on Node.js 14: https://github.com/nodejs/undici/runs/6260101390?check_suite_focus=true How is it that CI doesn't catch this?

Great question :)

Looks like this recent PR introduced the one I'm facing now:

https://github.com/nodejs/undici/pull/1309/files#diff-17e5e8b1a57b5f2366ef52769f8c28b48d1ab1e755408107e6705eaecbf38217R305

**Comment by matthewlilley** [comment] 2022-05-02 17:46
It would probably be worth auditing the use of these operators in this library, as this is the second instance in the past couple of weeks. Unforutnately this is blocking production builds on numerous apps for us at the moment.

**Comment by ronag** [comment] 2022-05-02 18:23
I think we disable fetch for node < 16 which is why CI doesn't catch it. Not sure how/where users are using fetch on Node < 16.

**Comment by mcollina** [comment] 2022-05-02 18:28
fetch does not work in node v14 because there are no whatwg streams in core

**Comment by matthewlilley** [comment] 2022-05-02 18:54
Further detail of usage can be found here:

https://github.com/graphprotocol/graph-client/issues/34

**Comment by matthewlilley** [comment] 2022-05-02 18:57
Specific usage is here: https://github.com/ardatan/whatwg-node/blob/master/packages/cross-undici-fetch/package.json

**Comment by mcollina** [comment] 2022-05-02 19:16
I don't understand. Can you articulate?

**Comment by matthewlilley** [comment] 2022-05-02 19:26
I shared the depedency graph in that post. 

I guess cross-undici-fetch is not actually using this in Node v14 environment

https://github.com/ardatan/whatwg-node/blob/223320ae3f30aa4fc76a06bdcab1eb2dd0e9b63a/packages/cross-undici-fetch/dist/create-node-ponyfill.js#L72

Undici targets engines 14 & 16.

**Comment by mcollina** [comment] 2022-05-02 19:32
I still don't understand what point are you trying to make.

**Comment by n1ru4l** [comment] 2022-05-02 19:37
Hey @matthewlilley, the referenced code should not run at all on Node.js 14 as `cross-undici-fetch` only uses `undici` conditionally.
This is very likely related to the bundler and NOT an issue within undici.

**Comment by matthewlilley** [comment] 2022-05-02 19:50
> Hey @matthewlilley, the referenced code should not run at all on Node.js 14 as `cross-undici-fetch` only uses `undici` conditionally. This is very likely related to the bundler and NOT an issue within undici.

Yeah, this is what I was thinking.

> I still don't understand what point are you trying to make.

I'm trying to understand where the problem is? @graphql-mesh?

The consumer of the @graphql-mesh code generated SDK is simply a Next.js application. I'm assuming the issue isn't with Next.js?

**Comment by n1ru4l** [comment] 2022-05-02 19:53
@matthewlilley Probably the Next.js compiler.

You can close this issue here and the discussion can continue on the one your created for graph-client. I am certain we all will find a solution.

**Comment by matthewlilley** [comment] 2022-05-02 19:54
@n1ru4l Thanks. I'll ping Vercel team about this. Sorry for being persistant, like I said this is blocking us on being able to deploy a number of applications right now.

**Closed** 2022-05-02 19:57 UTC
Labels: bug

**Comment by mcollina** [comment] 2022-05-02 22:06
It might be that a fix should be done here, but it might require a bit more explanation and a test case to reproduce.

**Comment by matthewlilley** [comment] 2022-05-02 22:55
> It might be that a fix should be done here, but it might require a bit more explanation and a test case to reproduce.

@mcollina For now Vercel have enabled Node 16 so this is no longer an issue for us.

Not much of a test case, but if you want to reproduce.

git clone https://github.com/sushiswap/interface.git
pnpm i
pnpx turbo run build --scope=furo

**Comment by deanhaleem** [comment] 2022-05-10 15:53
@ronag  In my case we're deploying to AWS Lambda. Bundling with webpack results in a smaller deployment package.
