### ISSUE TITLE
Improve BalancedPool balancing algorithm

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#1065] opened 2021-10-18 10:05 UTC
Currently `BalancedPool` use a simple round robin algorithm if the target upstream is not available.

A more nuanced algorithm could easily produce better  performance.

This is a good paper describing a better algorithm: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.863.3985&rep=rep1&type=pdf.

**Comment by jodevsa** [comment] 2021-10-19 12:05
@mcollina what is the reason behind introducing the balancedPool? Is it to support distributing the requests to multiple upstreams?

**Comment by mcollina** [comment] 2021-10-19 12:35
Yes exactly. There can be a few situations where deploying a separate load balancer in front of a pool of services is not an option.

**Comment by jodevsa** [comment] 2021-11-01 08:48
@delvedor 

Regarding

>     // we should be able to find the next node in 1 array scan,
>     // if we don't, it means that we are in an infinite loop

https://github.com/elastic/elastic-transport-js/blob/main/src/pool/WeightedConnectionPool.ts#L54

I believe this assumption is wrong. 

Lets say you have 3 servers with the following weights [90,10]:

> GCD =10 
> maxWeight= 90 
> currentWight = maxWeight= 90 

So it will need 8 iterations to go from currentWeight=90 to currentWeight=10. 

This is why the algorithm mentioned in the table uses an infinite loop.

**Comment by jodevsa** [comment] 2022-07-05 21:27
Hi guys, I finally have a vacation so hopefully I'll be able to wrap this this things 🙏  I was stuck at testing and currently working on rebasing after the new factory thingy changes. 


I need some help. So I've been writing tests and I noticed a behaviour in the algorithm where one server would be chosen for so many times. I'll try to explain it via an example:

Let us assume that we have 2 upstreams A, and B, with initial weights of 50 for both. Also let us assume that our dynamic weights logic would have a penalty of 19 points if the upstream request fails. if B fails the weight of B would be 31 and the weight of A would stay 50. the current weight would be around 50 and the algorithm would decrease that weight every N iterations by the GCD which is "1" in our case GCD(50,31).  So then the current weight is decreased every N iterations (2 in our case) by the GCD. This would result in the algorithm choosing server A for more than 78 times `(((50-11)/1) *2`.

 It would be very helpful if someone else can validate my findings and check if this is an acceptable behaviour. I'm also up for a call if anyone would like to discuss this further :)

**Comment by mcollina** [comment] 2022-07-05 21:47
I think 78 times is not that bad from my understanding.

If we are under _low load_, always picking the same server is not a problem. If we are under high load, 78 times does not look to be a long wait, less than a second if we are sending around 100 req/sec.

How does the math look like for like 3 or 5 servers?

**Comment by jodevsa** [comment] 2022-07-06 17:29
@mcollina  do we have an estimate about how many upstreams would probably be added? like a max of 100? 

I'm asking because currently the algorithm suffers from a case where the complexity could be up to O(maxWeight) if the GCD between all the weights is 1. We could optimise that to be O(N) by either calculating the next lower weight from currentWeight or keep it the logic the same and make sure we don't end up with weights that has 

I've also noticed that the elastic-transport-js library has a bug due to this assumption https://github.com/elastic/elastic-transport-js/blob/main/src/pool/WeightedConnectionPool.ts#L54

```
    // we should be able to find the next node in 1 array scan,
    // if we don't, it means that we are in an infinite loop
```

This is wrong especially when the GCD is 1. This is why they use a `while(true)` in the algorithm mentioned in the paper. The worst case is that we need to loop maxWeight times to find the next lower weight

**Comment by mcollina** [comment] 2022-07-06 21:56
I would not expect more than 100 peers.

**Comment by jodevsa** [comment] 2022-07-07 21:31
I'm seeing a weird behaviour where I have 3 upstreams (A,B,C) and only 1 of them goes down C. After C is down  A, B will also emit a disconnect event `.on('disconnect')` with a  disconnect socket idle timeout. Does this ring a bell @mcollina? if not I'l try to prepare a test where I can reproduce the problem.

**Comment by mcollina** [comment] 2022-07-07 22:05
Looks like a bug to me.

**Comment by jodevsa** [comment] 2022-10-14 22:03
HI @mcollina, can we close this issue now?

**Comment by mcollina** [comment] 2022-10-15 07:33
yes

**Closed** 2022-10-15 07:33 UTC
Labels: enhancement, good first issue
