### ISSUE TITLE
unidici doesn't play nice with webpack

### ISSUE THREAD

**Issue by uriva** [nodejs/undici#2015] opened 2023-03-18 18:00 UTC
I am writing a package in deno, and compiling it into npm.

Somehow unidici gets in the compiled target.

I then use webpack because I want to use this package in react setup.

webpack refuses to process unidici because of two dependencies: util/types and stream/web

I haven't found a polyfill for them.

Any idea what can be done?

this is my webpack config

```
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin");

const path = require("path");

module.exports = {
  mode: "production",
  entry: "./src/index.js",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
  },
  plugins: [new NodePolyfillPlugin()],
  resolve: {
    fallback: {
      perf_hooks: false,
      async_hooks: false,
      dns: false,
      tls: false,
      child_process: false,
      fs: false,
      net: require.resolve("net-websocket-polyfill"),
      diagnostics_channel: require.resolve("diagnostics_channel"),
      worker_threads: require.resolve("bthreads"),
    },
  },
};
```

**Comment by KhafraDev** [comment] 2023-03-18 18:23
this is a duplicate of #1992

**Closed by KhafraDev** 2023-03-18 18:23 UTC
Labels: enhancement
