### ISSUE TITLE
NextJS: Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by Ziothh** [nodejs/undici#3134] opened 2024-04-17 10:22 UTC
## Bug Description

When importing an elastic search package in a NextJS 14 project I get this error:

```
 ⨯ ../../node_modules/.pnpm/undici@6.13.0/node_modules/undici/lib/web/fetch/util.js
Module parse failed: Unexpected token (874:57)
|       // 5. If object is not a default iterator object for interface,
|       //    then throw a TypeError.
>       if (typeof this !== 'object' || this === null || !(#target in this)) {
|         throw new TypeError(
|           `'next' called on an object that does not implement interface ${name} Iterator.`

Import trace for requested module:
../../node_modules/.pnpm/undici@6.13.0/node_modules/undici/lib/web/fetch/util.js
../../node_modules/.pnpm/undici@6.13.0/node_modules/undici/lib/web/fetch/headers.js
../../node_modules/.pnpm/undici@6.13.0/node_modules/undici/index.js
../../node_modules/.pnpm/@elastic+transport@8.5.1/node_modules/@elastic/transport/lib/connection/UndiciConnection.js
../../node_modules/.pnpm/@elastic+transport@8.5.1/node_modules/@elastic/transport/lib/connection/index.js
../../node_modules/.pnpm/@elastic+transport@8.5.1/node_modules/@elastic/transport/index.js
../../node_modules/.pnpm/@elastic+enterprise-search@8.6.1/node_modules/@elastic/enterprise-search/index.js
../api/src/drivers/search/getEnterpriseSearchClient.ts
../api/src/drivers/search/AppSearchDriver.ts
../api/src/app/App.ts
../api/src/app/index.ts
./src/app/api/graphql/route.ts
```

## Environment
OS: MacOS Sonoma v14.4.1
NextJS version: v14.2.1

```
$ node --version
v18.19.0
```

**Comment by Uzlopak** [comment] 2024-04-17 10:32
Upstream issue in nextjs. Duplicate of #2954

**Closed by Uzlopak** 2024-04-17 10:32 UTC
Labels: bug

**Comment by ygweric** [comment] 2024-06-25 11:46
latest next.js fix this bug,
` "next": "14.2.4",` in my project
