### ISSUE TITLE
Undici throws a terminated error

### ISSUE THREAD

**Issue by Eddy84** [nodejs/undici#1490] opened 2022-06-12 08:00 UTC
## Bug Description

I have a bug with graphl-codegen which is very likely caused by undici closing the connection and sending a terminated signal?

I have double checked my backend with various graphql clients and plain http requests doing the introspection query, the bug is definitely in undici.

The server receives the request, but it is terminated.

A stacktrace is included below:

Here is the related issue
https://github.com/dotansimha/graphql-code-generator/issues/7934

## Reproducible By

See the linked issue above

## Expected Behavior

Return a response

## Logs & Screenshots

See below

## Environment

- Ubuntu 20 LTS
- undici 5.1

### Additional context

Stacktrace:

```
` Exited with an error DetailedError: Failed to load schema
    at loadSchema (/home/eduard/Projects/ecommerce/frontend/node_modules/@graphql-codegen/cli/bin.js:504:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/eduard/Projects/ecommerce/frontend/node_modules/@graphql-codegen/cli/bin.js:1034:65 {
  details: '\n' +
    '        Failed to load schema from http://localhost/service:\n' +
    '\n' +
    '        terminated\n' +
    '        TypeError: terminated\n' +
    '    at Fetch.onAborted (/home/eduard/Projects/ecommerce/frontend/node_modules/undici/lib/fetch/index.js:1893:49)\n' +
    '    at Fetch.emit (node:events:390:28)\n' +
    '    at Fetch.terminate (/home/eduard/Projects/ecommerce/frontend/node_modules/undici/lib/fetch/index.js:77:10)\n' +
    '    at Object.onError (/home/eduard/Projects/ecommerce/frontend/node_modules/undici/lib/fetch/index.js:2027:34)\n' +
    '    at Request.onError (/home/eduard/Projects/ecommerce/frontend/node_modules/undici/lib/core/request.js:237:27)\n' +
    '    at errorRequest (/home/eduard/Projects/ecommerce/frontend/node_modules/undici/lib/client.js:1711:13)\n' +
    '    at Socket.onSocketClose (/home/eduard/Projects/ecommerce/frontend/node_modules/undici/lib/client.js:985:5)\n' +
    '    at Socket.emit (node:events:390:28)\n' +
    '    at TCP.<anonymous> (node:net:687:12)\n' +
    '    \n' +
    '        GraphQL Code Generator supports:\n' +
    '          - ES Modules and CommonJS exports (export as default or named export "schema")\n' +
    '          - Introspection JSON File\n' +
    '          - URL of GraphQL endpoint\n' +
    '          - Multiple files with type definitions (glob expression)\n' +
    '          - String in config file\n' +
    '    \n' +
    '        Try to use one of above options and run codegen again.\n' +
    '    \n' +
    '      ',
  source: 'src/',
  context: [Object: null prototype] {}
}
Something went wrong Failed to load schema for "src/"
        Failed to load schema from http://localhost/service:

        terminated
        TypeError: terminated
    at Fetch.onAborted (/home/eduard/Projects/ecommerce/frontend/node_modules/undici/lib/fetch/index.js:1893:49)
    at Fetch.emit (node:events:390:28)
    at Fetch.terminate (/home/eduard/Projects/ecommerce/frontend/node_modules/undici/lib/fetch/index.js:77:10)
    at Object.onError (/home/eduard/Projects/ecommerce/frontend/node_modules/undici/lib/fetch/index.js:2027:34)
    at Request.onError (/home/eduard/Projects/ecommerce/frontend/node_modules/undici/lib/core/request.js:237:27)
    at errorRequest (/home/eduard/Projects/ecommerce/frontend/node_modules/undici/lib/client.js:1711:13)
    at Socket.onSocketClose (/home/eduard/Projects/ecommerce/frontend/node_modules/undici/lib/client.js:985:5)
    at Socket.emit (node:events:390:28)
    at TCP.<anonymous> (node:net:687:12)
    
        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named export "schema")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
          - String in config file
    
        Try to use one of above options and run codegen again.
`
```

**Comment by mcollina** [comment] 2022-06-12 10:17
Thanks for reporting. 
Can you provide steps to reproduce with just Undici? We often need a reproducible example, e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by d1urno** [comment] 2022-07-11 06:33
@Eddy84 I'm experiencing the same issue, did you manage to solve this?

**Comment by d1urno** [comment] 2022-07-11 16:22
Downgrading node version from 18 to 16 (stable) did the trick for me.

**Comment by LiamKarlMitchell** [comment] 2022-07-14 05:36
Same issue, but already on v16.14.0, v16.16.0 made no difference and it was working last week.
Laravel Lighthouse + Graphql code gen.

**Comment by hpiaia** [comment] 2022-07-27 20:47
@LiamKarlMitchell did you found any solution for that?
I am trying to use it with Laravel Lighthouse and have the same problem.
Node v16.16.0

**Comment by thomasaull** [comment] 2022-07-27 23:05
@hpiaia Check my comment in this other issue https://github.com/dotansimha/graphql-code-generator/issues/7934#issuecomment-1166520696 for a workaround.

**Comment by LiamKarlMitchell** [comment] 2022-07-27 23:20
Options request shouldn't have a Content-Length set.

Below is a middleware, which can be added to App/Http/Middlewares and put
into lighthouse middlewares config array.
It does add it to every POST request however for the graphql endpoint.

https://gist.github.com/LiamKarlMitchell/18f1e43ae6b772864d1b6a6ec1f71ba9

Works for me for a temp work-around until this can be resolved upstream.

**Comment by hpiaia** [comment] 2022-07-31 06:13
@thomasaull @LiamKarlMitchell,
I got another solution for that, just use node-fetch instead of undici for consuming the api.

```
schema:
  - http://localhost:8000/graphql:
      customFetch: 'node-fetch'
```

Reference:
https://www.graphql-code-generator.com/docs/config-reference/schema-field#customfetch

**Comment by mcollina** [comment] 2022-07-31 20:03
I'm closing this as `won't fix`. I will happy to review again when/if we have a reproduction for the problem.

**Closed by mcollina** 2022-07-31 20:03 UTC
Labels: bug

**Comment by thomasaull** [comment] 2022-08-01 07:52
@mcollina I'd be happy to provde a reproduction. However since this is happening in a mixedx project with php laravel and javascript, I'm not sure what would be the best way to do this?

**Comment by mcollina** [comment] 2022-08-01 11:33
Try to reproduce with just undici and Node.js. Things that work well:

1. use wireshark to see what's going on at the protocol level
2. use net.createServer to reproduce that server

**Comment by thomasaull** [comment] 2022-08-03 08:15
@mcollina Had no luck reproducing it with node :-/

**Comment by nvx0** [comment] 2022-08-24 21:23
any fix? i tried to fetch from local and it failed with error
```bash
(node:14784) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/deps/undici/undici:6245
            fetchParams.controller.controller.error(new TypeError("terminated", {
                                                    ^

TypeError: terminated
    at Fetch.onAborted (node:internal/deps/undici/undici:6245:53)
    at Fetch.emit (node:events:537:28)
    at Fetch.terminate (node:internal/deps/undici/undici:5502:14)
    at Object.onError (node:internal/deps/undici/undici:6336:36)
    at Request.onError (node:internal/deps/undici/undici:2055:31)
    at errorRequest (node:internal/deps/undici/undici:3964:17)
    at Socket.onSocketClose (node:internal/deps/undici/undici:3426:9)
    at Socket.emit (node:events:537:28)
    at TCP.<anonymous> (node:net:747:14) {
  [cause]: SocketError: closed
      at Socket.onSocketClose (node:internal/deps/undici/undici:3414:35)
      at Socket.emit (node:events:537:28)
      at TCP.<anonymous> (node:net:747:14) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: undefined,
      localPort: undefined,
      remoteAddress: undefined,
      remotePort: undefined,
      remoteFamily: undefined,
      timeout: undefined,
      bytesWritten: 195,
      bytesRead: 30087
    }
  }
}

Node.js v18.4.0
```

**Comment by michaelglass** [comment] 2023-08-17 22:47
happens periodically for us as well using node 18 with undici 5.22.1. No clear reproducer but we see it daily.

**Comment by jacobshirley** [comment] 2023-10-04 09:11
Happens to us, using Node 20 in a Google Cloud Functions, however works fine locally

**Comment by kevinrss01** [comment] 2024-03-18 11:50
Happens also periodically for me using node 20 and nest.js - No clear reproducer but we see it daily.
Happens only on long request (+15min)

**Comment by Shabinder** [comment] 2024-03-18 12:05
+1, Affected by this, inconsistently, no defined cause.

**Comment by undergroundwires** [comment] 2024-03-28 19:33
Happens when IPv6 is disabled. Reproduce on Ubuntu:

```
  echo '1' | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6 > /dev/null
  echo '1' | sudo tee /proc/sys/net/ipv6/conf/default/disable_ipv6 > /dev/null
```

Fetch usage with node results in exit code `13`.
