### ISSUE TITLE
CI Failing

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#1909] opened 2023-02-04 11:07 UTC
Can we at least disable it if we can't get it to pass?

**Comment by KhafraDev** [comment] 2023-02-04 15:43
If the WPT runner is hanging I think I have an idea, but very rarely are the runners even making it up to those tests.

Some tests that have been failing:
- test/agent.js
- test/redirect-stream.js

**Comment by lukekarrys** [comment] 2023-02-08 03:09
I noticed some runs timing out on node 18 + ubuntu also: https://github.com/nodejs/undici/actions/runs/4106521639/jobs/7084868359. Is this the same failure as the node 19 CI?

**Comment by KhafraDev** [comment] 2023-02-08 06:12
No, that seems to be an issue where the websocket wpts are hanging, probably because a socket isn't being closed somewhere.

**Comment by KhafraDev** [comment] 2023-02-08 19:34
```
 # Subtest: test/connect-timeout.js
    # Subtest: priotorise socket errors over timeouts
        1..1
        not ok 1 - should be equal
          ---
          compare: ===
          at:
            line: 16
            column: 9
            file: test/connect-timeout.js
          stack: |
            test/connect-timeout.js:16:9
          source: |2
                .catch((err) => {
                  t.equal(err.code, 'ENOTFOUND')
            --------^
                })
          diff: |
            --- expected
            +++ actual
            @@ -1,1 +1,1 @@
            -ENOTFOUND
            +UND_ERR_CONNECT_TIMEOUT
          ...
        
        # failed 1 test
    not ok 1 - priotorise socket errors over timeouts # time=1087.081ms
```
on node v16.8

**Comment by Uzlopak** [comment] 2024-02-14 16:59
@nodejs/undici 

This should be fixed. The case on node 16 is not reproducable anymore as the tests dont run anymore on node 16, as ReadableStream is not a global in node.

**Closed** 2024-02-14 17:32 UTC
Labels: bug
