### ISSUE TITLE
Missing headers

### ISSUE THREAD

**Issue by jamesdiacono** [nodejs/undici#2384] opened 2023-10-27 09:31 UTC
Starting with Node.js 20.8.1, a Request derived from another Request can lose the original request's headers.

```javascript
const original = new Request("http://localhost", {
    headers: {foo: "bar"}
});
console.log(original.headers); // {foo: "bar"}

const wrapper = new Request(original, {method: "HEAD"});
console.log(wrapper.headers); // {}
```

The correct behaviour, as demonstrated by previous versions of Undici, Deno, and browsers, is for the headers to be retained.

This bug only occurs if a non-empty object is passed as the `init` parameter of the second Request constructor (in this example, `{method: "HEAD"}`).

# Analysis

When `init` is non-empty, a branch is followed to check the original request's headers:

https://github.com/nodejs/undici/blob/3a77cbb471b76175898d8b094beb9b40ceadd671/lib/fetch/request.js#L418

The original headers (as a `Headers` object) are passed to `fillHeaders`, which expects either an array or a plain object:

https://github.com/nodejs/undici/blob/3a77cbb471b76175898d8b094beb9b40ceadd671/lib/fetch/request.js#L439

The `fillHeaders` function attempts to copy over the headers, but treats the `Headers` object as a plain object, and thus copies nothing:

https://github.com/nodejs/undici/blob/3a77cbb471b76175898d8b094beb9b40ceadd671/lib/fetch/headers.js#L58

Consequently, the headers are missing from the new Request.

**Comment by ronag** [comment] 2023-10-27 09:38
@KhafraDev

**Comment by KhafraDev** [comment] 2023-10-27 13:39
duplicate of https://github.com/nodejs/node/issues/50263

**Closed by KhafraDev** 2023-10-27 13:39 UTC
Labels: bug
