### ISSUE TITLE
Uncatchable error is thrown when a HTTPS post request fails

### ISSUE THREAD

**Issue by SammyWhamy** [nodejs/undici#867] opened 2021-07-08 10:32 UTC
## Bug Description
When making an HTTPS post request to a URL that doesn't respond/exist, an AssertionError is thrown that cannot be caught by the consumer.

## Reproducible By
Wrap a post request to an unreachable URL in a try...catch
Observe how the script is terminated without the error being caught

### Code example:
```js
import {request} from 'undici'
try {
  await request("https://thisis.not/avalid/url", {method: "POST");
} catch {
  console.log("Error caught, this never happens");
}
```

## Expected Behavior
The promise should be rejected so that the error can be caught and handled by the consumer

## Logs
```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(this.servername)

    at TLSSocket.<anonymous> (C:\path\node_modules\undici\lib\core\connect.js:61:11)
    at TLSSocket.emit (node:events:377:35)
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='
}
```

## Environment
Windows 10, Node v16.2.0

**Comment by vocafeuvre** [comment] 2021-07-09 02:04
I'm getting this too, it's caused by an assert call inside the error handler of the socket created by the request. Right now I'm commenting that line as a workaround

**Comment by mcollina** [comment] 2021-07-10 11:24
@vocafeuvre would you like to send a PR?

**Comment by joaopedrocampos** [comment] 2021-07-10 16:27
Hey guys! If still up to, I would love to try this fix 🙏

**Comment by mcollina** [comment] 2021-07-10 21:51
go for it!

**Comment by vocafeuvre** [comment] 2021-07-11 13:39
@mcollina yeah i have the fix in my fork, i'm opening a PR now

**Comment by ronag** [comment] 2021-07-11 20:21
Merged fix

**Closed** 2021-07-11 20:21 UTC
Labels: bug
