### ISSUE TITLE
Cannot read properties of undefined (reading 'timeoutType')

### ISSUE THREAD

**Issue by AkihiroEmiya** [nodejs/undici#1843] opened 2022-12-28 01:18 UTC
## Bug Description

Hello ! I have a problem, I wanted to launch my bot on my VPS (hosted by O2Switch) but I'm getting this weird error that I never seen before.
This error don't occur when I remove the client.login() line. 
Note that this code works indeed well on my personnal computer.
My VPS is using node JS version 16.17.1

```
TypeError: Cannot destructure property 'exports' of 'undefined' as it is undefined.
    at new Parser (/home/mzyu2532/test/node_modules/undici/lib/client.js:420:34)
    at connect (/home/mzyu2532/test/node_modules/undici/lib/client.js:1077:23)
/home/mzyu2532/test/node_modules/undici/lib/client.js:1184
        if (socket[kParser].timeoutType !== TIMEOUT_IDLE) {
                            ^

TypeError: Cannot read properties of undefined (reading 'timeoutType')
    at _resume (/home/mzyu2532/test/node_modules/undici/lib/client.js:1184:29)
    at resume (/home/mzyu2532/test/node_modules/undici/lib/client.js:1148:3)
    at connect (/home/mzyu2532/test/node_modules/undici/lib/client.js:1133:3)
   ```
Edit, this seems to be provocated by :
```
RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
    at lazyllhttp (/home/mzyu2532/test/node_modules/undici/lib/client.js:356:28)
```

## Reproducible By

on a O2Switch VPS, starting a node app with this code as index :
```js
const { Client, Events, GatewayIntentBits } = require('discord.js');
const { token } = require('./config.json');

const client = new Client({ intents: [GatewayIntentBits.Guilds] });

client.once(Events.ClientReady, c => { console.log(`Ready! Logged in as ${c.user.tag}`); });

client.login(token);
```

## Dependencies
```json
  "dependencies": {
    "discord.js": "^14.7.1",
    "JSON": "^1.0.0"
  }
 ```

## Unsatisfactory Solution

Launching this script from a ssh on my personnal computer.
*I would like to understand where the problem comes from*

## Environment

VPS : O2Switch
Node version : 16.17.1
Linux version : 4.18.0-372.19.1.lve.el7h.x86_64 *got from uname -r*
Heap Memory :
```
{
  total_heap_size: 4964352,
  total_heap_size_executable: 524288,
  total_physical_size: 3853632,
  total_available_size: 4342066688,
  used_heap_size: 4137768,
  heap_size_limit: 4345298944,
  malloced_memory: 254096,
  peak_malloced_memory: 91840,
  does_zap_garbage: 0,
  number_of_native_contexts: 1,
  number_of_detached_contexts: 0,
  total_global_handles_size: 8192,
  used_global_handles_size: 3040,
  external_memory: 314973
}
```
*got from ``console.log(require('v8').getHeapStatistics())``*

**Comment by KhafraDev** [comment] 2022-12-28 15:29
duplicate of #1634, help would be appreciated fixing it

**Closed** 2022-12-28 15:29 UTC
Labels: bug

**Comment by AkihiroEmiya** [comment] 2022-12-28 16:07
@KhafraDev The error does not seem to be caused in the same way. In my case, WebAssembly is correctly defined.

**Comment by KhafraDev** [comment] 2022-12-28 16:16
Different causes but the same bug, it looks like this is an with the browser terminal (and using ssh will fix this issue):
```
 I opened my local machine's terminal, accessed the app via ssh, and reuploaded the code then it worked fine.
```

https://stackoverflow.com/a/69879116/15299271

**Comment by AkihiroEmiya** [comment] 2022-12-28 16:34
Yeah, as I mentionned it too in the ``Unsatisfactory Solution`` section.

But I wanted to potentially find a solution to fix the problem.

I understood at one point that it could be due to insufficient RAM? I don't know if this could be an interesting way to explore to solve the problem.
Since this kind of error seems to happen mostly on VPS, one could think that it could come from a fictitious RAM limitation set by the distributor.

**Comment by lmclarke** [comment] 2023-01-20 03:35
Same issue. I am using ssh.

> node index.js

```
(node:21662) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/home/tfzmud/.asdf/tfz-bot/node_modules/undici/lib/client.js:1191
        if (socket[kParser].timeoutType !== TIMEOUT_IDLE) {
                            ^

TypeError: Cannot read properties of undefined (reading 'timeoutType')
    at _resume (/home/tfzmud/.asdf/tfz-bot/node_modules/undici/lib/client.js:1191:29)
    at resume (/home/tfzmud/.asdf/tfz-bot/node_modules/undici/lib/client.js:1155:3)
    at connect (/home/tfzmud/.asdf/tfz-bot/node_modules/undici/lib/client.js:1140:3)

```

**Comment by KhafraDev** [comment] 2023-01-23 20:12
The error occurs when the llhttp webassembly fails to load. With the recent v5.16.0 release, you should get a much better error detailing what happened.

**Comment by lmclarke** [comment] 2023-01-23 22:40
```
/home/tfzmud/tfz-bot/node_modules/undici/lib/client.js:355
  return await WebAssembly.instantiate(mod, {
                           ^

RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
    at lazyllhttp (/home/tfzmud/tfz-bot/node_modules/undici/lib/client.js:355:28)

```
New error with v5.16.0. I have plenty of memory, so not sure what this could mean. Documenting for posterity.

**Comment by KhafraDev** [comment] 2023-01-24 00:08
v8 reserves a lot of virtual memory to prevent out-of-bounds memory access (simply speaking). There's nothing undici can do to fix this.

See:
- https://github.com/nodejs/node/issues/41319#issuecomment-1001025128 (including the linked paper)
- https://github.com/webpack/webpack/issues/15584#issuecomment-1146566931 (which includes a potential solution)
